### PR TITLE
Check if the update contains a 'message' field.

### PR DESCRIPTION
**Pull request by Dimentium**
Otherwise we will fail if the update e.g. contains 'edited_message' instead of 'message'

### CODE REVIEW

**Comment by bobuk** [comment]
there's two different problems:
1. it will be better to catch all the other errors with one try/except
2. you've added logging, it's not used in this code before, so you need to remove it or add logging support for the whole library :)

**Comment by Dimentium** [comment]
> there's two different problems:
> 
> 1. it will be better to catch all the other errors with one try/except
> 2. you've added logging, it's not used in this code before, so you need to remove it or add logging support for the whole library :)

1. That's not an error. The field 'message' is related to the 'message' type update, which is just one of a few. More details here: https://core.telegram.org/bots/api#update
2. added import :)

**Comment by Dimentium** [comment]
Hi!
I'll try to rework this part soon.

**Comment by bobuk** [comment]
there's a conflict on your branch

**Pull request closed without merging**
